### ISSUE TITLE
[Bug] Can't change text prompt after initial load for awq-int4-flux.1-t5xxl

### ISSUE THREAD

**Issue by akagohary** [mit-han-lab/ComfyUI-nunchaku#238]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/ComfyUI-nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. I will do my best to describe the issue in English.

### Describe the Bug

Everything works if its the first run and the first load up, subsequent runs with different seeds also works, once you change the text prompt it fails and crashes throwing this error, this only happens with "awq-int4-flux.1-t5xxl.safetensors"

```
got prompt
Requested to load FluxClipModel_
loaded completely 5910.73881225586 487.23095703125 False
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x88 (0x7fe938980598 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x55 (0x7fe93891c21d in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3e2 (0x7fe938d2d402 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x54e1f (0x7fe938d30e1f in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x55840 (0x7fe938d31840 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4600e2 (0x7fe92b2600e2 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x7fe93895d439 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x721e78 (0x7fe92b521e78 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x722291 (0x7fe92b522291 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```

didn't know which repo i should've posted this bug to, since idk where the T5 feedback should go, am trying it out and am liking the results although it gives drastically different results between seeds unlike "t5xxl_fp8_e4m3fn_scaled.safetensors"

### Environment

Arch Linux x86_64, 6.14.9-arch1-1, pytorch 2.8dev, Build cuda_12.8.r12.8/compiler.35583870_0, python 3.11.11

### Reproduction Steps

Load your workflow with Nonchaku Clip loader v2, write the text prompt, run it, change the text prompt, It'll crash and core dump.

**Comment by dioscuri0860** [comment]
first image work fine...
second prompt insert and run click...
stuck ComfyUI

**Comment by JIKBG** [comment]
这是啥情况，你们用我的邮箱了的开心？我没有提问呀？密码丢了？




 
 
  
 
  ----- 原始邮件 -----
  
***@***.***>
  
***@***.***>等2人
  
主题：Re: [mit-han-lab/ComfyUI-nunchaku] [Bug] Can't change text prompt after initial load for awq-int4-flux.1-t5xxl (Issue #238)
  
日期：2025年06月03日 15:34:17
  

 
 

 
  
  dioscuri0860 left a comment 
  (mit-han-lab/ComfyUI-nunchaku#238)
  
 first image work fine...
 second prompt insert and run click...
 stuck ComfyUI

**Comment by AlexYez** [comment]
The same problem with awq-int4-flux.1-t5xxl.safetensors, only first generation works

**Comment by zmwv823** [comment]
#### Same on win10+py311+cuda128+torch2.7.
#### First time generation and not change prompt works well, once change prompt, raise this error.
```
got prompt
Requested to load FluxClipModel_
loaded partially 280.85185604095454 280.84912109375 0
!!! Exception during processing !!! CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 69, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 166, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 228, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\comfy\text_encoders\flux.py", line 53, in encode_token_weights
    t5_out, t5_pooled = self.t5xxl.encode_token_weights(token_weight_pairs_t5)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 68, in encode_token_weights
    r = (torch.cat(output, dim=-2).to(model_management.intermediate_device()), first_pooled)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
#### Optional solution:
Use comfy offical dual_clip_loader with t5xxl_fp8, super fast on rtx3050laptop and seems more accuracy on text-generation.

![Image](https://github.com/user-attachments/assets/1148a75e-07bd-4812-8f42-93321f37d1c3)

**Comment by lmxyy** [comment]
should be fixed in mit-han-lab/ComfyUI-nunchaku#256

**Comment by akagohary** [comment]
still the same issue

```
loaded completely 5791.30131225586 487.23095703125 False
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x88 (0x7f7c71580598 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x55 (0x7f7c7151c21d in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3e2 (0x7f7c7194e402 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x54e1f (0x7f7c71951e1f in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x55840 (0x7f7c71952840 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4600e2 (0x7f7c63e600e2 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f7c7155d439 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #7: <unknown function> + 0x721e78 (0x7f7c64121e78 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x722291 (0x7f7c64122291 in /data1/ComfyUI/venv/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```

@lmxyy  you are too quick to close the issue without getting feedback from the people testing out the tools with you, thats demoralizing my man

**Comment by akagohary** [comment]
> should be fixed in [#256](https://github.com/mit-han-lab/ComfyUI-nunchaku/pull/256)

you were right its fixed thats why i deleted my comment, i kept pulling dev without restarting then tried to check main again which undid the dev pull and restarted so that threw me through a loop, but finally i pulled dev and restarted now i can change the prompt and it keeps going no problem,

where can we post feedback for the generations with your t5 tho ? it varies alot between generations which can be good or bad depends on what the user wants, but flux t5 fp16 doesn't behave like that, not even the fp8 scaled one.

**Comment by lmxyy** [comment]
Hi @akagohary, thanks for the feedback!
I wasn’t able to exactly reproduce the error on my end, but based on your log, it seems the issue may have been caused by storing the T5 weights on the CPU while trying to access them with a CUDA kernel. I’ve pushed a fix for that.
Apologies for closing the issue before you had a chance to test it. With flooding incoming issues, I’ve been closing resolved ones to keep my TODO list manageable and stay focused. That said, feel free to reopen the issue or create a new one if the problem persists — I'm happy to take another look.

**Comment by lmxyy** [comment]
> > should be fixed in [#256](https://github.com/mit-han-lab/ComfyUI-nunchaku/pull/256)
> 
> you were right its fixed, i pulled dev and restarted now i can change the prompt and it keeps going no problem,
> 
> where can we post feedback for the generations tho ?

Just in the issue, in our Slack or Discord.

**Comment by lmxyy** [comment]
I would try to reply to all the comments. But some may be missed, as currently, I am almost developing and maintaining the codebase alone.

**Comment by lmxyy** [comment]
Typically, all the comments on Discord and Slack got replied.

**Comment by akagohary** [comment]
> I would try to reply to all the comments. But some may be missed, as currently, I am almost developing and maintaining the codebase alone.

i love your work, it gave me the sdxl days speed on my 3060 with flux quality, can't complain, keep it up.

> where can we post feedback for the generations with your t5 tho ? it varies alot between generations which can be good or bad depends on what the user wants, but flux t5 fp16 doesn't behave like that, not even the fp8 scaled one.

i edited my post with some comments about the t5, will do further experimentation and i'll be joining your discord

kudos.
